In [1]:
import os
import pickle

import numpy as np

import itertools as it
import random, math

In [2]:
os.getcwd()

'/home/iclab/yunjo-server/dl-4-tsc/GeneralizedModel'

In [7]:
y_num = []
result_path = "./results"
folder_names = os.listdir(result_path)
folder_names.sort()

for folder_name in folder_names:
    if folder_name.startswith("KEmoWork_19fold_"):
        print(folder_name)
        path = os.path.join(result_path, folder_name, "tune_00/cnnM/it_00/predictions.txt")
        print(path)
        if not os.path.exists(path):
            continue
        with open(path, 'r') as f:
            lines = f.readlines()
            y_num.append(len(lines[0].strip().split()))

KEmoWork_19fold_00
./results/KEmoWork_19fold_00/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_01
./results/KEmoWork_19fold_01/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_02
./results/KEmoWork_19fold_02/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_03
./results/KEmoWork_19fold_03/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_04
./results/KEmoWork_19fold_04/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_05
./results/KEmoWork_19fold_05/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_06
./results/KEmoWork_19fold_06/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_07
./results/KEmoWork_19fold_07/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_08
./results/KEmoWork_19fold_08/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_09
./results/KEmoWork_19fold_09/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_10
./results/KEmoWork_19fold_10/tune_00/cnnM/it_00/predictions.txt
KEmoWork_19fold_11
./results/KEmoWork_19fold_11/tune_00/cnnM/it_00/predictions.txt
KEmo

In [8]:
y_num

[151,
 149,
 150,
 140,
 140,
 145,
 151,
 147,
 145,
 144,
 145,
 144,
 146,
 142,
 146,
 146,
 149,
 147,
 144]

In [7]:
from sklearn.metrics import precision_score, accuracy_score, recall_score, f1_score, roc_auc_score

print(accuracy_score(y_true, y_pred))
print(1-roc_auc_score(y_true, y_pred_probabilities, multi_class='ovo'))

0.952054794520548
0.02064393939393938


In [33]:
from collections import Counter

count_dict = Counter(y_true)

for key, value in count_dict.items():
    print(f"{key}: {value}")

0: 66
1: 80


In [34]:
from collections import Counter

count_dict = Counter(y_pred)

for key, value in count_dict.items():
    print(f"{key}: {value}")

0: 63
1: 83


In [2]:
os.chdir('./archives')

In [3]:
dir_data = os.getcwd()
filename = 'mts_archive/WESAD/x_13_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  WESAD = pickle.load(f)

In [4]:
np.array(WESAD.data).shape

(75, 600)

In [35]:
np.expand_dims(np.array(WESAD.data), 2)

array([[[0.92553653],
        [0.93771946],
        [0.92555738],
        ...,
        [0.64482103],
        [0.65148308],
        [0.65166415]],

       [[0.94231506],
        [0.92666323],
        [0.93303821],
        ...,
        [0.63365029],
        [0.63583153],
        [0.63330016]],

       [[0.65242092],
        [0.6526435 ],
        [0.65211288],
        ...,
        [0.63659018],
        [0.66059996],
        [0.65199729]],

       ...,

       [[0.96100088],
        [0.96133326],
        [0.96044748],
        ...,
        [0.94283551],
        [0.94684111],
        [0.9409468 ]],

       [[0.94752273],
        [0.9446055 ],
        [0.94826863],
        ...,
        [0.94974868],
        [0.94687354],
        [0.9455933 ]],

       [[0.94610834],
        [0.94619241],
        [0.94684008],
        ...,
        [0.94678419],
        [0.94852562],
        [0.94847725]]])

In [11]:
dir_data = os.getcwd()
filename = 'mts_archive/KEmoWork/x_13_6.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f)

In [12]:
np.array(KEMOWORK.data).shape

(147, 80)

In [13]:
np.expand_dims(np.array(KEMOWORK.data), 2)

array([[[1.        ],
        [0.59748764],
        [0.55133131],
        ...,
        [0.19280024],
        [0.28024578],
        [0.31522349]],

       [[0.54032127],
        [0.55559775],
        [0.54864086],
        ...,
        [0.3114977 ],
        [0.30700574],
        [0.31679844]],

       [[0.31911304],
        [0.29349961],
        [0.3031903 ],
        ...,
        [0.28285678],
        [0.26732053],
        [0.26099371]],

       ...,

       [[0.36816413],
        [0.37325343],
        [0.38069944],
        ...,
        [0.3395144 ],
        [0.38253748],
        [0.38228017]],

       [[0.38017446],
        [0.40139321],
        [0.3814486 ],
        ...,
        [0.30796329],
        [0.38409078],
        [0.3873089 ]],

       [[0.33650119],
        [0.37001065],
        [0.3600567 ],
        ...,
        [0.35396212],
        [0.37952165],
        [0.30310696]]])

In [3]:
dir_data = os.getcwd()
filename = 'KEmoWork/S22/S22.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f, encoding='latin1')

In [6]:
KEMOWORK['signal']['EEG']

In [4]:
KEMOWORK['signal']['TEMP'].shape

(2944, 1)

In [13]:
KEMOWORK['label']['STRESS']

array([[ 0.],
       [ 0.],
       [ 0.],
       ...,
       [20.],
       [20.],
       [20.]])

In [16]:
np.mean(KEMOWORK['label']['STRESS'])

11.696133333333334

In [18]:
for i in range(0, 7460, 100):
    print(np.mean(KEMOWORK['label']['STRESS'][i:i+4]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
5.0
10.0
13.0
15.0
15.0
5.0
5.5
10.0
10.0
10.0
15.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0


In [14]:
len(KEMOWORK['label']['STRESS'])

7500

In [4]:
dir_data = os.getcwd()
filename = 'WESAD/S7/S7.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  WESAD = pickle.load(f, encoding='latin1')

In [4]:
WESAD['signal']['wrist']['ACC'].shape

(207776, 3)

In [53]:
np.array(WESAD['label'])

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [7]:
dir_data = os.getcwd()
filename = 'mts_archive/KEmoWork/x_2_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f, encoding='latin1')

In [9]:
np.array(KEMOWORK.data).shape

(743, 40)

In [11]:
filename = 'mts_archive/KEmoWork/y_2.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  LABEL = pickle.load(f, encoding='latin1')

In [14]:
len(LABEL)

743

In [15]:
np.expand_dims(np.array(KEMOWORK.data[0]),2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [6]:
filename = 'mts_archive/WESAD/y_4.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  LABEL = pickle.load(f, encoding='latin1')

In [7]:
LABEL

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0]

In [118]:
filename = 'mts_archive/WESAD/x_4_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  DATA = pickle.load(f, encoding='latin1')

In [119]:
len(DATA.data)

72

In [120]:
len(DATA.data[0])

600

In [4]:
SUBJECTS_IDS = list(it.chain(range(2, 12), range(13, 18)))

n = 15
test_sets = [SUBJECTS_IDS[i::n] for i in range(n)]

In [5]:
test_sets

[[2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [13],
 [14],
 [15],
 [16],
 [17]]

In [9]:
result = []
for test_set in test_sets:
    rest = [x for x in SUBJECTS_IDS if x not in test_set]
    val_set = random.sample(rest, math.ceil(len(rest) / 5))
    train_set = [x for x in rest if x not in val_set]
    result.append({"train": train_set, "val": val_set, "test": test_set})

In [10]:
result

[{'train': [3, 4, 5, 6, 7, 10, 11, 13, 14, 15, 16],
  'val': [9, 8, 17],
  'test': [2]},
 {'train': [2, 4, 6, 7, 9, 10, 11, 13, 14, 15, 17],
  'val': [16, 8, 5],
  'test': [3]},
 {'train': [2, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17],
  'val': [13, 14, 3],
  'test': [4]},
 {'train': [2, 3, 4, 7, 9, 11, 13, 14, 15, 16, 17],
  'val': [8, 6, 10],
  'test': [5]},
 {'train': [2, 3, 4, 5, 7, 8, 10, 11, 13, 14, 15],
  'val': [9, 16, 17],
  'test': [6]},
 {'train': [2, 3, 4, 5, 6, 8, 9, 10, 14, 15, 16],
  'val': [13, 17, 11],
  'test': [7]},
 {'train': [2, 4, 5, 7, 9, 10, 11, 13, 14, 15, 17],
  'val': [6, 3, 16],
  'test': [8]},
 {'train': [2, 3, 4, 5, 8, 10, 11, 14, 15, 16, 17],
  'val': [6, 7, 13],
  'test': [9]},
 {'train': [3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16],
  'val': [15, 17, 2],
  'test': [10]},
 {'train': [2, 3, 4, 6, 7, 9, 10, 13, 14, 15, 16],
  'val': [8, 17, 5],
  'test': [11]},
 {'train': [2, 3, 4, 5, 6, 7, 9, 10, 14, 15, 17],
  'val': [16, 11, 8],
  'test': [13]},
 {'train': [2, 3, 5, 