In [30]:
import os
import pickle

import numpy as np

import itertools as it
import random, math

In [41]:
# os.chdir('./archives')

In [33]:
dir_data = os.getcwd()
filename = 'mts_archive/WESAD/x_2_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  WESAD = pickle.load(f)

In [40]:
np.array(WESAD.data).shape

(71, 600)

In [35]:
np.expand_dims(np.array(WESAD.data), 2)

array([[[0.92553653],
        [0.93771946],
        [0.92555738],
        ...,
        [0.64482103],
        [0.65148308],
        [0.65166415]],

       [[0.94231506],
        [0.92666323],
        [0.93303821],
        ...,
        [0.63365029],
        [0.63583153],
        [0.63330016]],

       [[0.65242092],
        [0.6526435 ],
        [0.65211288],
        ...,
        [0.63659018],
        [0.66059996],
        [0.65199729]],

       ...,

       [[0.96100088],
        [0.96133326],
        [0.96044748],
        ...,
        [0.94283551],
        [0.94684111],
        [0.9409468 ]],

       [[0.94752273],
        [0.9446055 ],
        [0.94826863],
        ...,
        [0.94974868],
        [0.94687354],
        [0.9455933 ]],

       [[0.94610834],
        [0.94619241],
        [0.94684008],
        ...,
        [0.94678419],
        [0.94852562],
        [0.94847725]]])

In [36]:
dir_data = os.getcwd()
filename = 'mts_archive/KEmoWork/x_2_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f)

In [39]:
np.array(KEMOWORK.data).shape

(149, 40)

In [38]:
np.expand_dims(np.array(KEMOWORK.data), 2)

array([[[0.13844583],
        [0.13844583],
        [0.15473357],
        ...,
        [0.08143877],
        [0.10587035],
        [0.11401425]],

       [[0.11401425],
        [0.11401425],
        [0.08958261],
        ...,
        [0.09772645],
        [0.08143877],
        [0.08143877]],

       [[0.08143877],
        [0.10587035],
        [0.09772645],
        ...,
        [0.10587035],
        [0.11401425],
        [0.10587035]],

       ...,

       [[0.94299287],
        [0.95113678],
        [0.95113678],
        ...,
        [0.95113678],
        [0.95928062],
        [0.95928062]],

       [[0.95928062],
        [1.        ],
        [0.94299287],
        ...,
        [0.95113678],
        [0.94299287],
        [0.95113678]],

       [[0.94299287],
        [0.96742458],
        [0.95928062],
        ...,
        [0.97556842],
        [0.96742458],
        [0.95928062]]])

In [12]:
dir_data = os.getcwd()
filename = 'KEmoWork/S3/S3.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f)

In [13]:
KEMOWORK['label']['STRESS']

array([[ 0.],
       [ 0.],
       [ 0.],
       ...,
       [20.],
       [20.],
       [20.]])

In [16]:
np.mean(KEMOWORK['label']['STRESS'])

11.696133333333334

In [18]:
for i in range(0, 7460, 100):
    print(np.mean(KEMOWORK['label']['STRESS'][i:i+4]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
5.0
10.0
13.0
15.0
15.0
5.0
5.5
10.0
10.0
10.0
15.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0


In [14]:
len(KEMOWORK['label']['STRESS'])

7500

In [4]:
dir_data = os.getcwd()
filename = 'WESAD/S7/S7.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  WESAD = pickle.load(f, encoding='latin1')

In [4]:
WESAD['signal']['wrist']['ACC'].shape

(207776, 3)

In [53]:
np.array(WESAD['label'])

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [7]:
dir_data = os.getcwd()
filename = 'mts_archive/KEmoWork/x_2_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  KEMOWORK = pickle.load(f, encoding='latin1')

In [9]:
np.array(KEMOWORK.data).shape

(743, 40)

In [11]:
filename = 'mts_archive/KEmoWork/y_2.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  LABEL = pickle.load(f, encoding='latin1')

In [14]:
len(LABEL)

743

In [15]:
np.expand_dims(np.array(KEMOWORK.data[0]),2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [6]:
filename = 'mts_archive/WESAD/y_4.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  LABEL = pickle.load(f, encoding='latin1')

In [7]:
LABEL

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0]

In [118]:
filename = 'mts_archive/WESAD/x_4_0.pkl'

with open(os.path.join(dir_data, filename), 'rb') as f:
  DATA = pickle.load(f, encoding='latin1')

In [119]:
len(DATA.data)

72

In [120]:
len(DATA.data[0])

600

In [4]:
SUBJECTS_IDS = list(it.chain(range(2, 12), range(13, 18)))

n = 15
test_sets = [SUBJECTS_IDS[i::n] for i in range(n)]

In [5]:
test_sets

[[2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [13],
 [14],
 [15],
 [16],
 [17]]

In [9]:
result = []
for test_set in test_sets:
    rest = [x for x in SUBJECTS_IDS if x not in test_set]
    val_set = random.sample(rest, math.ceil(len(rest) / 5))
    train_set = [x for x in rest if x not in val_set]
    result.append({"train": train_set, "val": val_set, "test": test_set})

In [10]:
result

[{'train': [3, 4, 5, 6, 7, 10, 11, 13, 14, 15, 16],
  'val': [9, 8, 17],
  'test': [2]},
 {'train': [2, 4, 6, 7, 9, 10, 11, 13, 14, 15, 17],
  'val': [16, 8, 5],
  'test': [3]},
 {'train': [2, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17],
  'val': [13, 14, 3],
  'test': [4]},
 {'train': [2, 3, 4, 7, 9, 11, 13, 14, 15, 16, 17],
  'val': [8, 6, 10],
  'test': [5]},
 {'train': [2, 3, 4, 5, 7, 8, 10, 11, 13, 14, 15],
  'val': [9, 16, 17],
  'test': [6]},
 {'train': [2, 3, 4, 5, 6, 8, 9, 10, 14, 15, 16],
  'val': [13, 17, 11],
  'test': [7]},
 {'train': [2, 4, 5, 7, 9, 10, 11, 13, 14, 15, 17],
  'val': [6, 3, 16],
  'test': [8]},
 {'train': [2, 3, 4, 5, 8, 10, 11, 14, 15, 16, 17],
  'val': [6, 7, 13],
  'test': [9]},
 {'train': [3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16],
  'val': [15, 17, 2],
  'test': [10]},
 {'train': [2, 3, 4, 6, 7, 9, 10, 13, 14, 15, 16],
  'val': [8, 17, 5],
  'test': [11]},
 {'train': [2, 3, 4, 5, 6, 7, 9, 10, 14, 15, 17],
  'val': [16, 11, 8],
  'test': [13]},
 {'train': [2, 3, 5, 